apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: messaging
  name: messaging
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: messaging
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: messaging
        deploymentconfig: messaging
    spec:
      containers:
      - image: messaging
        #imagePullPolicy: Always
        name: messaging
        ports:
        - containerPort: 3000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: messaging-configmap
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

